// Comprehensive test data for Pet Dating App

export const testPets = [
  {
    id: 'pet_1',
    name: 'Luna',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 24,
    gender: 'female',
    distance: 2.5,
    photos: ['https://images.unsplash.com/photo-1633722715463-d30628519d14?w=400'],
    bio: 'Energetic golden girl who loves fetch and swimming! Always ready for adventures.',
    traits: ['Playful', 'Friendly', 'Trained'],
    personalityTags: ['Outgoing', 'Adventurous', 'Social'],
    favoriteActivities: ['Fetch', 'Swimming', 'Hiking'],
    vaccineStatus: 'vaccinated',
    isOnline: true,
    owner: { id: 'user_1', name: 'Sarah', avatar: 'https://i.pravatar.cc/150?img=1' },
  },
  {
    id: 'pet_2',
    name: 'Max',
    species: 'dog',
    breed: 'German Shepherd',
    age: 36,
    gender: 'male',
    distance: 3.2,
    photos: ['https://images.unsplash.com/photo-1568572933382-74d440642117?w=400'],
    bio: 'Loyal and protective companion. Love training and mental stimulation.',
    traits: ['Protective', 'Intelligent', 'Loyal'],
    personalityTags: ['Smart', 'Confident', 'Serious'],
    favoriteActivities: ['Training', 'Park Visits', 'Puzzle Games'],
    vaccineStatus: 'vaccinated',
    isOnline: true,
    owner: { id: 'user_2', name: 'Mike', avatar: 'https://i.pravatar.cc/150?img=2' },
  },
  {
    id: 'pet_3',
    name: 'Bella',
    species: 'cat',
    breed: 'Siamese',
    age: 18,
    gender: 'female',
    distance: 1.8,
    photos: ['https://images.unsplash.com/photo-1513245543132-31f0213d31cc?w=400'],
    bio: 'Elegant and affectionate. Loves cuddles and interactive play.',
    traits: ['Affectionate', 'Vocal', 'Playful'],
    personalityTags: ['Elegant', 'Chatty', 'Loving'],
    favoriteActivities: ['Playing', 'Cuddling', 'Sunbathing'],
    vaccineStatus: 'vaccinated',
    isOnline: false,
    owner: { id: 'user_3', name: 'Emma', avatar: 'https://i.pravatar.cc/150?img=3' },
  },
  {
    id: 'pet_4',
    name: 'Charlie',
    species: 'dog',
    breed: 'Beagle',
    age: 20,
    gender: 'male',
    distance: 4.1,
    photos: ['https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=400'],
    bio: 'Curious and adventurous little guy. Always sniffing around!',
    traits: ['Curious', 'Energetic', 'Social'],
    personalityTags: ['Mischievous', 'Friendly', 'Active'],
    favoriteActivities: ['Scent Work', 'Running', 'Sniffing'],
    vaccineStatus: 'vaccinated',
    isOnline: true,
    owner: { id: 'user_4', name: 'John', avatar: 'https://i.pravatar.cc/150?img=4' },
  },
  {
    id: 'pet_5',
    name: 'Mimi',
    species: 'cat',
    breed: 'Persian',
    age: 24,
    gender: 'female',
    distance: 2.9,
    photos: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400'],
    bio: 'Fluffy and calm. Perfect lap cat for quiet evenings.',
    traits: ['Calm', 'Quiet', 'Affectionate'],
    personalityTags: ['Calm', 'Sweet', 'Sensitive'],
    favoriteActivities: ['Lap Sitting', 'Grooming', 'Napping'],
    vaccineStatus: 'vaccinated',
    isOnline: false,
    owner: { id: 'user_5', name: 'Lisa', avatar: 'https://i.pravatar.cc/150?img=5' },
  },
  {
    id: 'pet_6',
    name: 'Rocky',
    species: 'dog',
    breed: 'Boxer',
    age: 30,
    gender: 'male',
    distance: 5.2,
    photos: ['https://images.unsplash.com/photo-1552053831-71594a27c62d?w=400'],
    bio: 'Strong and playful boxer. Loves wrestling and playing games!',
    traits: ['Playful', 'Strong', 'Goofy'],
    personalityTags: ['Fun', 'Playful', 'Energetic'],
    favoriteActivities: ['Wrestling', 'Ball Play', 'Jumping'],
    vaccineStatus: 'vaccinated',
    isOnline: true,
    owner: { id: 'user_6', name: 'David', avatar: 'https://i.pravatar.cc/150?img=6' },
  },
  {
    id: 'pet_7',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Maine Coon',
    age: 36,
    gender: 'male',
    distance: 3.5,
    photos: ['https://images.unsplash.com/photo-1520166446848-da506512c67d?w=400'],
    bio: 'Big gentle giant. Loves water and outdoor adventures.',
    traits: ['Gentle', 'Adventurous', 'Loyal'],
    personalityTags: ['Giant', 'Gentle', 'Adventurous'],
    favoriteActivities: ['Water Play', 'Outdoor Time', 'Climbing'],
    vaccineStatus: 'vaccinated',
    isOnline: true,
    owner: { id: 'user_7', name: 'Robert', avatar: 'https://i.pravatar.cc/150?img=7' },
  },
  {
    id: 'pet_8',
    name: 'Daisy',
    species: 'dog',
    breed: 'Cocker Spaniel',
    age: 22,
    gender: 'female',
    distance: 1.5,
    photos: ['https://images.unsplash.com/photo-1583511655857-d19db992cb74?w=400'],
    bio: 'Sweet and gentle spaniel. Great with everyone, loves cuddles!',
    traits: ['Gentle', 'Sweet', 'Obedient'],
    personalityTags: ['Sweet', 'Gentle', 'Loving'],
    favoriteActivities: ['Cuddles', 'Walks', 'Playing'],
    vaccineStatus: 'vaccinated',
    isOnline: false,
    owner: { id: 'user_8', name: 'Jessica', avatar: 'https://i.pravatar.cc/150?img=8' },
  },
];

export const testUsers = [
  {
    id: 'user_1',
    name: 'Sarah',
    email: 'sarah@example.com',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Dog lover and nature enthusiast',
    location: 'San Francisco, CA',
  },
  {
    id: 'user_2',
    name: 'Mike',
    email: 'mike@example.com',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Professional dog trainer',
    location: 'Oakland, CA',
  },
  {
    id: 'user_3',
    name: 'Emma',
    email: 'emma@example.com',
    avatar: 'https://i.pravatar.cc/150?img=3',
    bio: 'Cat enthusiast and artist',
    location: 'Berkeley, CA',
  },
  {
    id: 'user_4',
    name: 'John',
    email: 'john@example.com',
    avatar: 'https://i.pravatar.cc/150?img=4',
    bio: 'Adventure seeker',
    location: 'Palo Alto, CA',
  },
  {
    id: 'user_5',
    name: 'Lisa',
    email: 'lisa@example.com',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Quiet book lover with cats',
    location: 'Mountain View, CA',
  },
];

export const testConversations = [
  {
    id: 'conv_1',
    pet: testPets[0],
    messages: [
      { id: '1', sender: 'user_1', content: 'Hi! Luna is very friendly!', timestamp: new Date(Date.now() - 3600000) },
      { id: '2', sender: 'me', content: 'Great! Max would love to meet her!', timestamp: new Date(Date.now() - 3300000) },
      { id: '3', sender: 'user_1', content: 'Sure! How about this weekend?', timestamp: new Date(Date.now() - 3000000) },
    ],
    lastMessage: 'Sure! How about this weekend?',
    lastMessageTime: new Date(Date.now() - 3000000),
    unreadCount: 0,
  },
  {
    id: 'conv_2',
    pet: testPets[2],
    messages: [
      { id: '1', sender: 'user_3', content: 'Bella would love to play!', timestamp: new Date(Date.now() - 7200000) },
      { id: '2', sender: 'me', content: 'That sounds perfect! 😊', timestamp: new Date(Date.now() - 6900000) },
    ],
    lastMessage: 'That sounds perfect! 😊',
    lastMessageTime: new Date(Date.now() - 6900000),
    unreadCount: 0,
  },
];

export const testMatches = [
  testPets[0],
  testPets[2],
  testPets[4],
  testPets[6],
];

export const testPosts = [
  {
    id: 'post_1',
    author: testUsers[0],
    petId: 'pet_1',
    content: 'Luna just learned a new trick! 🎉 So proud of my girl!',
    timestamp: new Date(Date.now() - 7200000),
    likes: 12,
    comments: 3,
    liked: false,
  },
  {
    id: 'post_2',
    author: testUsers[1],
    petId: 'pet_2',
    content: 'Max passed his advanced training certification! 🏆',
    timestamp: new Date(Date.now() - 3600000),
    likes: 28,
    comments: 5,
    liked: true,
  },
  {
    id: 'post_3',
    author: testUsers[2],
    petId: 'pet_3',
    content: 'Bella is demanding her breakfast treats 😹',
    timestamp: new Date(Date.now() - 1800000),
    likes: 8,
    comments: 2,
    liked: false,
  },
  {
    id: 'post_4',
    author: testUsers[3],
    petId: 'pet_4',
    content: 'Charlie loves exploring the new hiking trail!',
    timestamp: new Date(Date.now() - 900000),
    likes: 15,
    comments: 4,
    liked: true,
  },
];

export const testComments = [
  {
    id: 'comment_1',
    author: testUsers[1],
    content: 'That\'s amazing! 🎉',
    timestamp: new Date(Date.now() - 7000000),
  },
  {
    id: 'comment_2',
    author: testUsers[2],
    content: 'So cute! Luna is beautiful ❤️',
    timestamp: new Date(Date.now() - 6800000),
  },
  {
    id: 'comment_3',
    author: testUsers[3],
    content: 'Congratulations Max! 🏅',
    timestamp: new Date(Date.now() - 3500000),
  },
];

// Test data summary
export const testDataSummary = {
  pets: testPets.length,
  users: testUsers.length,
  conversations: testConversations.length,
  matches: testMatches.length,
  posts: testPosts.length,
  comments: testComments.length,
};

export default {
  testPets,
  testUsers,
  testConversations,
  testMatches,
  testPosts,
  testComments,
  testDataSummary,
};
